inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
