require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Solid Cache in development too, so dev matches prod and the Section 5 rate
  # limiter is backed by the same durable (DB) store. Change to :null_store to
  # avoid any caching.
  config.cache_store = :solid_cache_store

  # Use S3 once AWS credentials exist; local disk until then (keeps dev working
  # without a bucket while exercising all upload code paths).
  config.active_storage.service =
    Rails.application.credentials.dig(:aws, :access_key_id).present? ? :amazon : :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Detect N+1 queries and unused eager loading via Bullet.
  config.after_initialize do
    Bullet.enable        = true
    Bullet.bullet_logger = true
    Bullet.rails_logger  = true
    Bullet.raise         = true
  end

  # Mission Control – Jobs dashboard (mounted dev-only at /jobs). Two adjustments so
  # its HTML UI works inside this API-only app:
  #   1. Render under ActionController::Base, not our ActionController::API
  #      ApplicationController (whose ExceptionHandler/rate_limit/lack of view+flash
  #      support otherwise breaks the dashboard).
  #   2. Skip HTTP Basic auth (on by default since v1.0) — unnecessary on localhost.
  # (Set here, not in an initializer: the engine applies these in before_initialize,
  # which runs before config/initializers.) Production gating comes in Section 14.
  config.mission_control.jobs.base_controller_class = "ActionController::Base"
  config.mission_control.jobs.http_basic_auth_enabled = false
end
